[package]
name = "mancala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "mancala-server"
path = "src/server.rs"

[[bin]]
name = "mancala-client"
path = "src/client.rs"
